study/post/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name='post'

urlpatterns = [
    path('',views.list, name='list'),
    path('write/',views.write, name='write'),
    path('show/<int:post_id>/', views.show, name='show'),
    path('updateget/<str:post_id>/', views.updateget, name='updateget'),
    path('deleteget/<int:post_id>/', views.deleteget, name='deleteget'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
    path('search/', views.search, name='search'),
]

urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

study/study/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

study/users/urls.py
from django.urls import path
from .views import *

app_name='users'

urlpatterns = [
    path('home/', home, name='home'),
    path('home/signup/', signup, name='signup'),
    path('home/login', login, name='login'),
    path('home/logout', logout, name='logout')
]

study/post/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    # writer는 django User model에 포함된 값만 저장될 수 있게 제약함.
    
    def __str__(self):
        return self.title
    
class PostImage(models.Model):
    post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE)
    # Post에 있는 내용물을 불러올 영역(?)
    
    image_file = models.ImageField(null=True, upload_to="images/", blank=True)
    # 앞으로 업로드 될 사진을 담을 영역 (?)
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.content

study/post/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    #작성하려고 했을 때 새 폼을 주는 것
    class Meta:
        model=Post
        fields=['title','content']
        
class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['comment']
        
class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

study/post/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Post, Image, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.views.decorators.http import require_POST
from django.db.models import Q
# Create your views here.

def list(request):
    posts = Post.objects.all()
    return render(request,'main.html', {'posts':posts})

def write(request): #새 글 폼 띄워줌, 게시글 저장
    #post랑 get의 차이: post는 비밀화되어있는 정보들 get은 주소창에 그대로 정보가 뜬다.
    #get은 비어있는 느낌, post는 꽉 차있는 느낌
    if request.method=='POST':
        form=PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.writer=request.user
            post.save()
            
            for img in request.FILES.getlist('image',None):
                Image.objects.create(post=post, image=img)
                
            return redirect('post:list')
    else:
        form=PostForm() #request는 현재 상황인데 없으니까 아예 새 포스트를 불러옴
        return render(request,'write.html', {'form':form})
    
def show(request, post_id):
    post = get_object_or_404(Post, pk =post_id)
    images=Image.objects.filter(post=post)
    comments = post.comment_set.all()  
    commentForm = CommentForm() 
    context = {
        'post': post,
        'images': images,
        'comments': comments,
        'commentForm': commentForm, 
    }
    return render(request, 'detail.html', context)

    # commentForm=CommentForm()
    # comment=get_object_or_404(Comment, pk=post_id)
    # return render(request, 'detail.html',
    # {'post':post, 'images':images, 'commentForm':commentForm})

# def update(request, pk):
#     post=Post.objects.get(id=pk)
#     if request.method=="POST":
#         post.title=request.POST['title']
#         post.content=request.POST['content']
#         post.writer=request.POST['writer']
        
#         post.save()
#         return redirect('post')
#     else:
#         postForm=PostForm
#         return render(request, updated.html)

@login_required(login_url='/accounts/home/login')
def deleteget(request, post_id):
    post=Post.objects.get(id=post_id)
    post.delete()
    return redirect('post:list')

    # if request.user==post.writer:
    #     if request.method=='POST':
    #         post.delete()
    #         return redirect('/')
    #     return render(request, 'delete.html', {'post':post})
    
    #     return redirect('post:show')
    # else:
    #     post.delete()
    #     return redirect('post:list')

def updateget(request, post_id):
    post=Post.objects.get(id=post_id)
    if request.method=='POST':
        postForm=PostForm(request.POST, request.FILES, instance=post)
        if postForm.is_valid():
            post=postForm.save(commit=False)
            post.modify_date=timezone.now()
            post.save()
            return redirect('/show/'+str(post_id), {'post':post})
    else:
        postForm=PostForm(instance=post)
        return render(request, 'updated.html', {'post':post})                
            
        # if request.method=='POST':
        #     postForm=PostForm(request.POST, request.FILES, instance=post)
        #     if postForm.is_valid(): #수정글 다 작성해서 저장할때
        #         post=postForm.save(commit=False)
        #         post.save()
        #         # return redirect(''+str(bid))
        #         return render(request, 'post:show', post_id )
        # else:
        #     postForm=PostForm(instance=post)
        # return render('post:') #수정버튼 눌렀을 때

@require_POST
def comments_create(request, pk):
    if request.user.is_authenticated:
        post=Post.objects.get(pk=pk)
        commentForm=CommentForm(request.POST)
        if commentForm.is_valid():
            comment=commentForm.save(commit=False)
            comment.post=post
            comment.writer=request.user
            comment.save()
        return redirect('post:show', pk)
    return redirect('accounts/home/login')
    
@require_POST
def comments_delete(request, pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.writer:
            comment.delete()
    return redirect('post:show', pk)

    # if request.users.is_authenticated:
    #     comment=get_object_or_404(Comment, pk=comment_pk)
    #     if request.user==comment.writer:
    #         comment.delete()
    # return redirect('post:show', post_pk)

@require_POST
def likes(request, post_pk):
    if request.user.is_authenticated:
        post=get_object_or_404(Post, pk=post_pk)
        if post.like_users.filter(pk=request.user.pk).exists():
            post.like_users.remove(request.user)
        else:
            post.like_users.add(request.user)
        return redirect('post:show', post_pk)
    return redirect('accounts/home/login')

# def search(request):
#         if request.method == 'POST':
#                 searched = request.POST['searched']
#                 # 검색창에 입력된 내용을 searched에 받음
#                 post1 = Post.objects.filter(name__contains=searched)
#                 # 그리고 그 변수가 데이터베이스에 사용자가 검색한 내용이 포함된 object에 있는지 찾아서
#                 # 찾은 내용을 post1에 담아 searched.html 페이지에 딕셔너리 형태로 반환해줌.
#                 context = {
#                     'searched':searched,
#                     'post1':post1
#                 }
#                 ret'searched':searchedurn render(request, 'searched.html', context)
#         else: # POST 방식이 아닐 경우, 빈 딕셔너리를 searched.html에 반환해줌.
#                 return render(request, 'searched.html', {})
#             #  request.POST[''] 안에 있는 searched는 검색창을 구현했던 nav 부분에서 
#             #  form 태그의 input 태그에 있는 name=searched의 searched를 의미합니다.


def search(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        search_word = set(searched.replace(',', ' ').split())
        
        q_objects = Q()
        for word in search_word:
            if word:  # 빈 문자열 필터링
                q_objects |= Q(title__icontains=word) | Q(content__icontains=word)
        
        # 검색 수행
        posts = Post.objects.filter(q_objects).distinct()
        
    context = {
        'searched':searched,
        'posts':posts
    }    
    
    return render(request, 'search.html', context)

study/post/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ post.title }}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <p id='title'>제목 : </p>
    <p class="form">{{ post.title }}</p>
    <p>날짜 : {{post.created_at}}</p>
    <p>내용 : {{ post.content }}</p>
    

    {% for img in image_file %}
        <img src="{{img.image_file.url}}" alt="Image">
    {%endfor%}
    <br><br>

    <h4>댓글 목록</h4>

    <!--read-->
    {% if comments %}
        <p><b>{{ comments|length }}개의 댓글이 있습니다.</b></p>
    {% endif %}
    <ul>
        
        {% for comment in comments %}
            <li>
                {{ comment.user }} - {{ comment.content }}
      
                <!--delete-->
                {% if user == comment.user %}
                    <form action="{% url 'post:comments_delete' post.pk comment.pk %}" method="POST">
                        {% csrf_token %}
                        <input type="submit" value="댓글 삭제">
                    </form>
                {% endif %}
            </li>
        {% empty %}
            <p>댓글이 없습니다.</p>
        {% endfor %}
    </ul>

    <hr>

    <!--create-->
    {% if request.user.is_authenticated %}
        <form action="{% url 'post:comments_create' post.pk %}" method="POST">
        {% csrf_token %}
            댓글 작성:{{ comment_form.as_p }} 
            <!--as.p comment_form 안에 담긴 form 전체를 가져온다.-->
            <input type="submit" value="댓글작성">
     </form>
    {% else %}
        <a href="{% url 'users:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
    {% endif %}

    <a href="{% url 'post:list' %}"><button>목록</button></a>
</body>
</html>

study/post/templates/edit.html
<!DOCTYPE html>
<html>
<head>
    <title>Edit Post</title>
</head>
<body>
    <h1>글 작성</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>제목 : {{ form.title }}</p>
        <p>내용 : {{form.content}}</p>
        사진<input type="file" name="image" aceept="image/*" multiple>
        <button type="submit">수정</button>
    </form>
    <a href="{% url 'post:list' %}"><button>목록</button></a>
</body>
</html>

study/post/templates/main.html
<!DOCTYPE html>
<html>
<head>
    <title>Post List</title>
</head>
<body>
    <form class="d-flex" method="POST" action="{% url 'post:search' %}">
        {% csrf_token %}        
        <input class="form-control me-2" type="search" placeholder="Search" name="searched" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"> Search </button>
    </form>
    <hr>
    <h1>목록</h1>
    <ul>
        {% for post in posts %}
        <li><a href="{% url 'post:show' post.id %}">{{ post.title }}</a>&nbsp;&nbsp;&nbsp;작성자: {{post.writer}}</p></li>
        {% endfor %}
    </ul>
    <a href="{% url 'post:write' %}">글 작성</a>
</body>
</html>

study/post/templates/search.html
{% block content %}
    {% if searched %}        
    <h1> 검색하신 {{ searched }} 레시피 정보입니다. </h1>
    <br>
    {% for post in posts %}        <!-- 검색 결과가 여러 개일 수 있기 때문에 반복문을 사용했습니다.  -->
    <a href="{% url 'post:show' post.id %}">{{ post.title }}</a>&nbsp;&nbsp;&nbsp;작성자: {{post.writer}}</p></li> <br>
<br>
    {% endfor %}
    {% else %}   <!-- 검색창에 아무것도 입력하지 않았을 경우 뜨는 메시지입니다. -->
    <h1> 찾고 있는 레시피의 제목이나 내용 키워드를 검색창에 입력해주세요. </h1>
    {% endif %}
{% endblock content %}

study/post/templates/updated.html
<html>
<head>
    <title>Update Post</title>
</head>
<body>
    <h1>글 수정</h1>
    <form action="{% url 'post:updateget' post.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ postForm.as_p }}
        <input multiple type="file" name="새이미지" accept="image/*" id="id_image">
        <button type="submit">저장</button>
        {% comment %} <input multiple type="file" name="image" aceept="image/*" id="id_image"> {% endcomment %}
    </form>
    <h2>기존 이미지</h2>
    <form method="post">
        {% csrf_token %}
        <ul>
            {% for image in images %}
                <li>
                    <img src="{{ image.image.url }}" alt="Image" style="max-width: 200px;">
                    {% comment %} {{form.remove_image.label_tag}}{{form.remove_image}} {% endcomment %}
                    <button type="submit" name="image_id" value="{{ image.id }}">삭제</button>
                </li>
            {% endfor %}
        </ul>
    </form>
</body>
</html>

study/post/templates/write.html
<!DOCTYPE html>
<html>
<head>
    <title>Create Post</title>
</head>
<body>
    <h1>글 작성</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>제목 : {{ form.title }}</p>
        <p>내용 : {{form.content}}</p>
        사진<input type="file" name="image" aceept="image/*" multiple>
        <button type="submit">저장</button>
    </form>
    <a href="{% url 'post:list' %}"><button>목록</button></a>
</body>
</html>